site_name: pydbantic
theme: readthedocs
markdown_extensions:
  - admonition
nav:
  - Pydbantic: index.md
  - Setup: setup.md
  - Quick Start: quick-start.md
  - Model Usage: model-usage.md
  - Database Usage: database-usage.md
  - Redis: redis-usage.md