site_name: pydbantic
theme: readthedocs
markdown_extensions:
  - admonition
dependencies:
 - sphinx<3.1.0
 - jinja2<3.1.0
nav:
  - Pydbantic: index.md
  - Setup: setup.md
  - Quick Start: quick-start.md
  - Tutorials: tutorials.md
  - Model Usage: model-usage.md
  - Database Usage: database-usage.md
  - Redis: redis-usage.md